services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0.19-ubi8
    ports:
      - 27017:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./data:/data/db
    restart: always
    user: 1000:1000
